version: '3.1'

services:
  web:
    build: .
    environment:
      USE_DB: "1"
      DEBUG: ""
      MYSQL_NAME: app
      MYSQL_USER: app
      MYSQL_HOST: db
      MYSQL_PASSWORD: passwd
      LOG_FORMAT: json
    ports:
      - 8000:8000

  job:
    build: .
    environment:
      MYSQL_NAME: app
      MYSQL_USER: app
      MYSQL_HOST: db
      MYSQL_PASSWORD: passwd
      LOG_FORMAT: json
    command: bash -c "/app/run_job.sh"
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.6.33
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:v2.9.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.1.4
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passwd
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/prometheus_docker-compose.yaml
